//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTag) DeepCopyInto(out *AutoTag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTag.
func (in *AutoTag) DeepCopy() *AutoTag {
	if in == nil {
		return nil
	}
	out := new(AutoTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoTag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTagList) DeepCopyInto(out *AutoTagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoTag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTagList.
func (in *AutoTagList) DeepCopy() *AutoTagList {
	if in == nil {
		return nil
	}
	out := new(AutoTagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoTagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTagObservation) DeepCopyInto(out *AutoTagObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTagObservation.
func (in *AutoTagObservation) DeepCopy() *AutoTagObservation {
	if in == nil {
		return nil
	}
	out := new(AutoTagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTagParameters) DeepCopyInto(out *AutoTagParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTagParameters.
func (in *AutoTagParameters) DeepCopy() *AutoTagParameters {
	if in == nil {
		return nil
	}
	out := new(AutoTagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTagSpec) DeepCopyInto(out *AutoTagSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTagSpec.
func (in *AutoTagSpec) DeepCopy() *AutoTagSpec {
	if in == nil {
		return nil
	}
	out := new(AutoTagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTagStatus) DeepCopyInto(out *AutoTagStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTagStatus.
func (in *AutoTagStatus) DeepCopy() *AutoTagStatus {
	if in == nil {
		return nil
	}
	out := new(AutoTagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.DynamicKey != nil {
		in, out := &in.DynamicKey, &out.DynamicKey
		*out = new(string)
		**out = **in
	}
	if in.DynamicKeySource != nil {
		in, out := &in.DynamicKeySource, &out.DynamicKeySource
		*out = new(string)
		**out = **in
	}
	if in.EntityId != nil {
		in, out := &in.EntityId, &out.EntityId
		*out = new(string)
		**out = **in
	}
	if in.EnumValue != nil {
		in, out := &in.EnumValue, &out.EnumValue
		*out = new(string)
		**out = **in
	}
	if in.IntegerValue != nil {
		in, out := &in.IntegerValue, &out.IntegerValue
		*out = new(int)
		**out = **in
	}
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.EntitySelector != nil {
		in, out := &in.EntitySelector, &out.EntitySelector
		*out = new(string)
		**out = **in
	}
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceToHostPropagation != nil {
		in, out := &in.ServiceToHostPropagation, &out.ServiceToHostPropagation
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToPGPropagation != nil {
		in, out := &in.ServiceToPGPropagation, &out.ServiceToPGPropagation
		*out = new(bool)
		**out = **in
	}
	if in.HostToPgPropagation != nil {
		in, out := &in.HostToPgPropagation, &out.HostToPgPropagation
		*out = new(bool)
		**out = **in
	}
	if in.PgToHostPropagation != nil {
		in, out := &in.PgToHostPropagation, &out.PgToHostPropagation
		*out = new(bool)
		**out = **in
	}
	if in.PgToServicePropagation != nil {
		in, out := &in.PgToServicePropagation, &out.PgToServicePropagation
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToPgPropagation != nil {
		in, out := &in.ServiceToPgPropagation, &out.ServiceToPgPropagation
		*out = new(bool)
		**out = **in
	}
	if in.AzureToPgPropagation != nil {
		in, out := &in.AzureToPgPropagation, &out.AzureToPgPropagation
		*out = new(bool)
		**out = **in
	}
	if in.AzureToServicePropagation != nil {
		in, out := &in.AzureToServicePropagation, &out.AzureToServicePropagation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}
