apiVersion: notification.dynatrace.crossplane.io/v1alpha1
kind: Email
metadata:
  name: email-notification
spec:
  forProvider:
    alertingProfileRef:
      name: my-profile
      policy:
        resolve: Always
        resolution: Required

    subject: My Subject
    notifyClosedProblems: true
    name: My email notification
    enabled: true

    body: "{ProblemDetailsHTML}"
    to:
    - crossplane-user@noreply.dynatrace.com
    bcc:
    - crossplane-user@noreply.dynatrace.com


  providerConfigRef:
    name: dynatrace-provider
