apiVersion: notification.dynatrace.crossplane.io/v1alpha1
kind: Email
metadata:
  name: email-notification
spec:
  forProvider:
    alertingProfileRef:
      name: my-profile

    sendEmailWhenProblemIsClosed: true
    subject: asdf

    displayName: My email notification
    enabled: true

    body: "{ProblemDetailsHTML}"
    to:
    - david.laubreiter@dynatrace.com
    bcc:
    - david.laubreiter@dynatrace.com


  providerConfigRef:
    name: dynatrace-provider
