apiVersion: notification.dynatrace.crossplane.io/v1alpha1
kind: Email
metadata:
  name: email-notification
spec:
  forProvider:
    alertingProfileRef:
      name: my-profile

    displayName: My email notification
    enabled: true
    sendEmailWhenProblemIsClosed: true
    subject: My errors
    body: "{ProblemDetailsHTML}"
    to:
    - david.laubreiter@dynatrace.com
    bcc:
    - david.laubreiter@dynatrace.com


  providerConfigRef:
    name: dynatrace-provider
