apiVersion: notification.dynatrace.crossplane.io/v1alpha1
kind: Slack
metadata:
  name: email-notification
spec:
  forProvider:
    alertingProfileRef:
      name: my-profile
      policy:
        resolve: Always
        resolution: Required

    active: true

    name: Something went wrong!
    channel: "#general"
    message: "Some message"
    url: "https://some-url.com"


  providerConfigRef:
    name: dynatrace-provider
