apiVersion: alerting.dynatrace.crossplane.io/v1alpha1
kind: Profile
metadata:
  name: my-profile
spec:
  forProvider:
    name: "My name"
    eventFilters:
    - type: PREDEFINED
      predefinedFilter:
        eventType: CUSTOM_APP_CRASH_RATE_INCREASED
        negate: true
    - type: CUSTOM
      customFilter:
        titleFilter:
          caseSensitive: true
          enabled: true
          negate: false
          operator: BEGINS_WITH
          value: asdf

    severityRules:
    - delayInMinutes: 45
      severityLevel: MONITORING_UNAVAILABLE
      tagFilterIncludeMode: INCLUDE_ALL
      tagFilter:
      - "asdf:fdas"

  providerConfigRef:
    name: dynatrace-provider
