apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-provider-pull-secret
type: Opaque
stringData:
  credentials: |
    {
      "auths": {
        "https://ghrc.io": {}
      }
    }
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-dynatrace
spec:
  package: ghcr.io/laubi/provider-dynatrace:0.0.1
  packagePullSecrets:
  - name: dynatrace-provider-pull-secret
---

apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
stringData:
  credentials: |
    {
      "url": "https://tenant.dynatrace.com",
      "token": "dt0c01.YOUR-TOKEN"
    }

---
apiVersion: dynatrace.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: dynatrace-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
