apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
stringData:
  credentials: |
    {
      "url": "https://tenant.dynatrace.com",
      "token": "dt0c01.YOUR-TOKEN"
    }

---
apiVersion: dynatrace.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: dynatrace-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
